apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-password
type: Opaque
stringData:
    GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:XzNeoHNw5wbHBoTP+Sz9NJTJkAJ1ayfItl8cbu4=,iv:tjj3HjIvSleCnJKuIzUlw00YSXDz9Jt6zyXdHaNjHhg=,tag:zzpbWJGDXFiokU4vhiK3Ng==,type:str]
sops:
    age:
        - recipient: age1kzhu2a3x49ucya85xsdhzu5vzy0l679k5k0gltephktkp7ed3s3qjwme6u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4NDk0OWRJSnA1ZENNU09j
            VTIydXBtbTdQeEVtdTVzMVF5RThXbEVQZ0NvCmxQMS8yKzBVTnlWTlNOaVhmT2l3
            eWdCd2dIYXdyTFFZU0pUcDIvRzEzWFkKLS0tIDcvUlpMM3ErWDg5d0xiaDdhRk80
            RXpRZ2R0RXUwbi9wRDc1V1h3dFJUUUkKVM03yEIxYyo1mhmQt4flwvCNA9U5BtCn
            +vB4vkPZgiuwL0NIxuiCCz5eRSKAbjjzB7Th+dgv91m5PSJjHhWDSA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-13T13:53:29Z"
    mac: ENC[AES256_GCM,data:+IVfd+7jUAhd+HcB8n0zrlIir9JL8kwzTRtH9wkNUJhfIi6NQHO2Lh52V4fCixv76uoL7uWrnCOyzi+4NYB7rK8wT6XvVQGdtsiOo6kqCQZJ6TEtZbD3tCRn869iDl6aTF7I18SVaNF7rOTH81erucFalLiStjX8W2oD8T6vKvY=,iv:pCKRmthf4UE8I6Zx3IUokhhHkOUrC2VL11SHYWIyzX8=,tag:VMq8OhUjXRBkirfJQsxPxQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
