apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-password
type: Opaque
stringData:
    GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:hc2qT0DBqnLIURdMuWcnTMrwzX3JLQvAnR5H8p0QVvrN,iv:eU0C5ZNVREISHslUw2k3B2lkVaWxsQXcVA7E9aacH+Y=,tag:cm8EkhkfgOu7EEnLfI//7g==,type:str]
sops:
    age:
        - recipient: age1kzhu2a3x49ucya85xsdhzu5vzy0l679k5k0gltephktkp7ed3s3qjwme6u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUGEyZGZpM2xYL2RXdWxS
            QUNXWnAxOTFlOUVtTjJwYXZGUCtOcjM3VWxVCjhHeUNXdjlCeFRrTjNQUi90Q0FH
            VkNaMFhBRG1HRHpvVzRSelQ4cG9yekkKLS0tIEUxdkg0dnpwR2hDY2pmUk0wR0dP
            Rm9JdDZlbUZmMUhRSUlnbHVpVDVjNTgKVx8fzf/PDrOy3kAwhZaBw+XIGzZrPI3d
            4zmrscxTO8/Bk/mJ80fQQXwrFIwJFe3qKoStj45eM16g2gbKJNaEhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-13T13:45:36Z"
    mac: ENC[AES256_GCM,data:teXOKhiJWPktbnAZR8udWXlVy4U6rJelkoN5a5yRMoNzhpwHiGLIKrSZQ/hN1HXH4n7ey8Jyrez3xhEb8l46dKaLx5ETrB9a6i1EOFNH1sRkUWaAm+43t/3pWBBzd67r1shiLhr5hbnSyi1/vgESckND5LJOvQKsQOF8peBPfso=,iv:mFd2wM8MqrvJ6H202wVJ27aRoGuUO960kRjMiXD+sV0=,tag:3iNSPA8820FmqjkcXLQ1YA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
